const CLOUDINARY_CLOUD_NAME: string = process.env.CLOUDINARY_CLOUD_NAME!;
const CLOUDINARY_API_KEY: string = process.env.CLOUDINARY_API_KEY!;
const CLOUDINARY_API_SECRET: string = process.env.CLOUDINARY_API_SECRET!;
const CLOUDINARY_POST = "reality-code/post";

export { CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET };
